<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <meta charset="utf-8">
    <style>
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Consolas'; }
			  @page {
		  size: 1210px 681px;
		  margin: 0;
		}

		@media print {
		  .remark-slide-scaler {
			width: 100% !important;
			height: 100% !important;
			transform: scale(1) !important;
			top: 0 !important;
			left: 0 !important;
		  }
		}
    small{
      font-size: 10px!important;
    }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>
  <body>
    <textarea id="source">

class: center, middle

# Programmation orientée objet :
# exceptions
<img height="200px" src="img/php_logo.png">

---
## Problématique

Lors de l'exécution d'un programme, tout ne se passe pas toujours comme prévu...

<img height="200px" src="img/crash.png">

--

* accès à un objet qui n'existe pas
* accès à un index qui dépasse le tableau
* calcul incorrect (division par 0)
* connexion à une base de données interrompue (coupure internet)
* ...

---
## Principe des exceptions

<img height="250px" src="img/erreur.png">

---
## Traiter l'erreur : lancer une exception

Lorsqu'une erreur est détectée, la classe responsable de l'erreur **lance** une erreur.

```php

class Calculatrice{

	function division($dividende, $diviseur){
		// Détection de l'erreur
		if(diviseur == 0){
			// Lancement ("throw") de l'erreur
			throw new DivisionParZeroException();
			// Après un throw, la fonction s'arrête
		}
		// Ici, tout va bien
		return $dividende / $diviseur;
	}
}

```

---
## Gérer l'erreur : attraper une exception

### La méthode propage l'erreur

```php
$calculette = new Calculatrice();

// Tout va bien
$calculette.division(3,2);

// L'exécution de la méthode s'arrête
// et une exception est lancée
$calculette.division(3,0);
```

---
## Gérer l'erreur : attraper une exception

### La méthode attrape l'erreur

```php
try{
	$calculette = new Calculatrice();
	// Tout va bien
	$calculette.division(3,2);
	// L'exécution du try s'arrête et une exception est lancée
	$calculette.division(3,0);
}catch(DivisionParZeroException $e){
	// L'exception est attrapée
	echo $e->getMessage();
}finally{
	// Bloc de code qui s'exécute quoi qu'il arrive
	// Après un bloc try ou un bloc catch
}
```

---
## Définition d'une exception personnalisée

```php
class DivisionParZeroException extends Exception {
}
```

---
## Coding time !

### Todo :

* Exercice 1 (Série 6)

* Exercice 2 (Série 6)

* Exercice 3 (Série 6)

<img height="400px" src="img/fast.gif">

    </textarea>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create();
    </script>
  </body>
</html>